services:
  redis:
    image: redis:6-alpine
    container_name: canguinha_redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: canguinha_web
    command: gunicorn canguinaProject.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2 --timeout 120
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - redis
    restart: on-failure

  worker:
    build: .
    container_name: canguinha_worker
    command: celery -A canguinaProject worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.prod
    depends_on:
      - redis
      - web
    restart: on-failure
